### ISSUE TITLE
导入中文乱码

### ISSUE THREAD

**Issue by yinanzhaobaima** [h4ckdepy/Un1kFiles#2]
<img width="501" alt="Snipaste_2022-01-28_12-12-39" src="https://user-images.githubusercontent.com/42661974/151486335-c85f3a53-6805-4179-b885-44d27b871001.png">
 尝试修改User options - Display - Character set 仍无法解决

**Comment by h4ckdepy** [comment]
您好 提供一下burpsuite版本。尝试修改字体为宋体试试。
burpsuitev1.7.26使用正常，burpsuitev2020.12.1使用正常。
